In [74]:
import xml.etree.ElementTree as ET

In [10]:
import numpy as np
import warnings

warnings.filterwarnings(action='ignore')

## <데이터 차원과 형태>

In [5]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
print(data.shape)
print(data.size)
print(data.ndim)
print(data.nbytes)
print(data.dtype)

(3, 2)
6
2
24
int32


## <수치형 데이터 타입>

In [11]:
print(np.array([1,2,3], dtype=np.int))
print(np.array([1,2,3], dtype=np.float))
print(np.array([1,2,3], dtype=np.complex))

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [12]:
## 형 변환
data = np.array([[1,2], [3,4], [5,6]], dtype = np.int)
data.astype(np.float)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## <메소드>

In [17]:
print(np.zeros((2,3)), end='\n\n')
print(np.ones(4), end='\n\n')
print(np.full(3,3.2), end='\n\n')

[[0. 0. 0.]
 [0. 0. 0.]]

[1. 1. 1. 1.]

[3.2 3.2 3.2]



In [19]:
data = np.ones(4)
data.fill(3)
print(data)

[3. 3. 3. 3.]


In [28]:
print(np.arange(0,12,4), end='\n\n')

# 4개의 포인트 설정하여 3개의 구간으로 나누기
print(np.linspace(0,16,4), end = '\n\n')

print(np.logspace(0,2,3))

[0 4 8]

[ 0.          5.33333333 10.66666667 16.        ]

[  1.  10. 100.]


In [33]:
x = np.array([-1,0,1])
y = np.array([-2,0,2])
x,y = np.meshgrid(x,y)
print(x, end='\n\n')
print(y)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]

[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]


In [34]:
# 0과 1사이의 랜덤 수
np.random.rand(2)

array([0.96537725, 0.98760822])

In [35]:
# 항등 행렬
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# diagonal matrix
np.diag(np.arange(0,30,10))

array([[ 0,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 20]])

## 인덱싱과 슬라이싱

In [41]:
a = np.arange(0, 11)
print(a[0])
print(a[-1])
print(a[0:5])
print(a[0:5:2])
print(a[:5])
print(a[-5:])
print(a[::-2])

0
10
[0 1 2 3 4]
[0 2 4]
[0 1 2 3 4]
[ 6  7  8  9 10]
[10  8  6  4  2  0]


In [42]:
a = np.array([[1,2,3,4],
             [11,12,13,14],
             [21,22,23,24],
             [31,32,33,34]])
print(a[:,1], end='\n\n')
print(a[1,:], end='\n\n')
print(a[:2,:2], end='\n\n')
print(a[2:,:2], end='\n\n')
print(a[::2,::2], end='\n\n')
print(a[1::2,1::2], end='\n\n')

[ 2 12 22 32]

[11 12 13 14]

[[ 1  2]
 [11 12]]

[[21 22]
 [31 32]]

[[ 1  3]
 [21 23]]

[[12 14]
 [32 34]]



In [44]:
# 0~1 사이에 11개 만들기 (같은 간격으로)
data = np.linspace(0,1,11)
print(data, end='\n\n')
print(data[np.array([0,2,4])], end='\n\n')
print(data[data>0.5], end='\n\n')
print(data[np.arange(2,5)], end='\n\n')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.  0.2 0.4]

[0.6 0.7 0.8 0.9 1. ]

[0.2 0.3 0.4]



## Resizing and Adding dim

In [45]:
# reshape
data = np.array([[1,2],
                 [3,4]])
np.reshape(data, (1,4))
data.flatten()

array([1, 2, 3, 4])

In [49]:
data = np.arange(5)
print(data, end = '\n\n')

# 행으로 쌓기
print(np.vstack((data, data, data)), end='\n\n')

# 열로 쌓기
print(np.hstack((data, data)))

[0 1 2 3 4]

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

[0 1 2 3 4 0 1 2 3 4]


In [54]:
# 넘파이 어레이끼리 합치기
a = np.arange(3)
b = np.arange(4)

np.concatenate((a,b))

array([0, 1, 2, 0, 1, 2, 3])

In [55]:
# 넘파이 어레이끼리 합치기 2
np.append(a, [3,4,5])

array([0, 1, 2, 3, 4, 5])

In [56]:
np.resize(b, (2,3))

array([[0, 1, 2],
       [3, 0, 1]])

In [93]:
# 정렬"
data = [[2,3,1], [9,8,7]]
np.sort(data)

array([[1, 2, 3],
       [7, 8, 9]])

## 수학 함수

In [63]:
print(np.sqrt(4), end='\n\n')
print(np.log2(8), end='\n\n')
print(np.log10(100), end='\n\n')

2.0

3.0

2.0



In [72]:
# 숫자 하나에 관련한 연산
data = np.array([2,3])
print(data*2)
print(data-1)
print()

# 리스트는 연산 불가능
data_list = [2,3]
print(data_list*2)
print(data_list-1)

[4 6]
[1 2]

[2, 3, 2, 3]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
a = np.array([1,2,3])
b = np.array([2,4,6])

# 각 어레이끼리의 연산
# 모든 연산을 각자의 위치에 맞게 된다. -> 리스트도 마찬가지
print(np.add(a,b), end='\n\n')
print(np.subtract(b,a), end='\n\n')
print(np.multiply(a,b), end='\n\n')
print(np.divide(b,a), end='\n\n')

In [78]:
data = np.arange(0,10)

print(np.mean(data))
print(np.std(data))
print(np.sum(data))
print(np.var(data))
# 모든 값의 곱
print(np.prod(data))
print(np.argmin(data), np.argmax(data))
print(np.all(data))
print(np.any(data))

4.5
2.8722813232690143
45
8.25
0
0 9
False
True


## Logical Expression

In [92]:
data = np.linspace(0,16,5)
print(data, end='\n\n')

print(np.where(data<5, data, 10*data), end='\n\n')
print(np.choose(2,data), end='\n\n')
print(np.nonzero(data), end='\n\n')
print(np.select([data<2, data>=2],[data-1,data*2]), end='\n\n')
print(np.logical_and(data>1, data<10), end='\n\n')
print(np.logical_or(data<1, data>15), end='\n\n')
print(np.logical_not(data>5), end='\n\n')

[ 0.  4.  8. 12. 16.]

[  0.   4.  80. 120. 160.]

8.0

(array([1, 2, 3, 4], dtype=int64),)

[-1.  8. 16. 24. 32.]

[False  True  True False False]

[ True False False False  True]

[ True  True False False False]



## sympy

In [94]:
import sympy

In [101]:
x = sympy.Symbol('x')
expr = 2*(x**2-x)-x*(x+1)
expr

2*x**2 - x*(x + 1) - 2*x


In [103]:
expr = 1/(x**2-1) + 1/(x+1)
expr

1/(x**2 - 1) + 1/(x + 1)